### ISSUE TITLE
is_absorbing w/o termination

### ISSUE THREAD

**Issue by capissimo** [PacktPublishing/Hands-On-Markov-Models-with-Python#4]
The function is_absorbing is wrongly tabbed and without completion:

def is_absorbing(self, state):
     """
     Checks if the given state is absorbing.
     Parameters
     ----------
     state: str
     The state for which we need to check whether it's absorbing
     or not.
     """
     state_index = self.index_dict[state]
     if self.transition_matrix[state_index, state_index]
     ?????

**Comment by capissimo** [comment]
SOLVED with this:
return True if self.transition_matrix[state_index, state_index] else False
Ple check if i'm right

**Comment by ankurankan** [comment]
@capissimo Yes, you are right. Has been fixed in the code now.
