### ISSUE TITLE
TypeError: 'numpy.bool_' object is not iterable

### ISSUE THREAD

**Issue by capissimo** [PacktPublishing/Hands-On-Markov-Models-with-Python#5]
This line in is_transient function:
transient_markov.is_transient('A')
gives an error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-6c27d64541ed> in <module>()
----> 1 transient_markov.is_transient('A')

<ipython-input-26-f82dd37c0851> in is_transient(self, state)
    124             The state for which the transient property needs to be checked.
    125         """
--> 126         if all(self.transition_matrix[~self.index_dict[state], self.index_dict[state]] == 0):
    127             return True
    128         else:

TypeError: 'numpy.bool_' object is not iterable

**Comment by capissimo** [comment]
SOLVED with prefixing np.all(...)

**Comment by ankurankan** [comment]
@capissimo Thanks for reporting the issue. Has been fixed in the code now.
