### ISSUE TITLE
machine learning classification for dependent categorical values presented in tabulate data?

### ISSUE THREAD

**Issue by Sandy4321** [PacktPublishing/Hands-On-Markov-Models-with-Python#7]
thanks for video 
https://www.youtube.com/watch?time_continue=2&v=Vcmjqx7lht0&feature=emb_logo
pgmpy Probabilistic Graphical Models using Python | SciPy 2015 | Ankur Ankan & Abinash Panda
and
https://hasgeek.com/anthillinside/2019/proposals/introduction-to-bayesian-networks-3-hour-workshop-S8SHqBNgG3R7CauAN2iUTY

can you help find examples to use this for machine learning classification for dependent categorical values presented in tabulate data?
is it possible to use dependency between many features for learning from data
for example  for pgmpy referencing to
model = BayesianModel([('D', 'G'), ('I', 'G'), ('I', 'S'), ('G', 'L')])
https://github.com/pgmpy/pgmpy/blob/dev/examples/Learning%20from%20data.ipynb

can it be
model = BayesianModel([('D', 'I', 'G', 'L', 'S'), ('I', 'G'), ('I', 'S'), ('G', 'L')])
or
model = BayesianModel([('D', 'I', 'S'), ('I', 'G'), ('I', 'S'), ('G', 'L')])
or in case no dependency like this
model = BayesianModel([])
lets say data looks like this
A     B         C     Target
a1  b3     c1        yes
a1  b1     c1        yes
a2  b2    c2         no
a3  b1    c1         no
a2  b2    c1         no
a1  b1    c2         yes

new data is given
A     B         C     
a1  b1     c2       
so what target will be predicted

**Comment by ankurankan** [comment]
@Sandy4321 For the data that you have given in the example, there are four random variables: `A`, `B`, `C`, and `Target`. So, you will need to create a Bayesian Network over these variables. A simple Naive Bayes model would have the structure:
```python
BayesianModel([('Target', 'A'), ('Target', 'B'), ('Target', 'C'), ('Target', 'D')])
```
Using the `pgmpy.models.NaiveBayes` class:
```python
model = NaiveBayes()
model.fit(data, parent_node='Target')
```

**Comment by Sandy4321** [comment]
may you share full example code
